language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - latest
install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
before_script:
  - go vet $(glide novendor)
  - golint $(glide novendor)
script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build ./mapping
  - go test -v -covermode=count -coverprofile=coverage.out ./mapping
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
