language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
before_script:
script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build ./mapping
  - GO15VENDOREXPERIMENT=1 go test $(glide novendor) -c -covermode=atomic -i
  - go vet ./mapping
  - golint .
  - golint mapping
